name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  audit:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.version }}

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go run honnef.co/go/tools/cmd/staticcheck@latest ./...

    - name: Install golint
      run: go run golang.org/x/lint/golint@latest ./...

    - name: Run tests
      run: go test -race -vet=off ./...
